name: 'Terraform CI/CD Pipeline'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform-init:
    name: 'Terraform Init'
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-south-1'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.3'

      - name: Terraform Init
        working-directory: dev
        run: terraform init

  terraform-fmt:
    name: 'Terraform Format'
    runs-on: ubuntu-latest
    needs: terraform-init

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.3'

      - name: Terraform Format
        working-directory: dev
        run: terraform fmt -recursive
      
      - name: Terraform Format
        working-directory: dev
        run: terraform fmt -check

  terraform-validate:
    name: 'Terraform Validate'
    runs-on: ubuntu-latest
    needs: terraform-fmt

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-south-1'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.3'

      - name: Terraform Validate
        working-directory: dev
        run: terraform validate
