name: 'Terraform CICD pipeline'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: terraform-runner
    environment: Dev
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-south-1'

    - name: 'Verify AWS Credentials'
      run: aws sts get-caller-identity

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.11.3'

  terraform_init:
    name: terraform Init
    runs-on: terraform-runner
    needs: terraform
    steps:
    - name: Terraform Init
      working-directory: dev
      run: terraform init

  terraform_format:
    name: terraform Format
    runs-on: terraform-runner
    needs: terraform_init
    steps:
    - name: Terraform format
      working-directory: dev
      run: terraform fmt

  terraform_validate:
    name: terraform Validate
    runs-on: terraform-runner
    needs: terraform_format
    steps:
    - name: Terraform validate
      working-directory: dev
      run: terraform validate
